# Generated by Django 4.2.5 on 2023-09-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_articletags_article_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField()),
                (
                    "article_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope",
                        to="articles.article",
                    ),
                ),
                (
                    "tag_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope",
                        to="articles.tag",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ArticleTags",
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
