# Generated by Django 4.2.5 on 2023-09-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_scope_delete_articletags_alter_article_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="scope",
            name="tag_ad",
        ),
        migrations.AddField(
            model_name="scope",
            name="tag_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.tag",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="scopes", through="articles.Scope", to="articles.tag"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.article"
            ),
        ),
    ]
