# Generated by Django 4.2.5 on 2023-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_options_remove_scope_tag_ad_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scope",
            old_name="article_id",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="scope",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="article",
            name="scopes",
            field=models.ManyToManyField(
                related_name="articles", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
