# Generated by Django 4.2.5 on 2023-09-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_rename_article_id_scope_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="articles.tag",
            ),
        ),
    ]
