# Generated by Django 4.2.5 on 2023-09-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_alter_scope_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="articles.article",
            ),
        ),
    ]
