# Generated by Django 4.2.5 on 2023-09-29 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_alter_scope_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scope",
            old_name="article",
            new_name="article_id",
        ),
        migrations.RenameField(
            model_name="scope",
            old_name="tag",
            new_name="tag_id",
        ),
    ]
