# Generated by Django 4.2.5 on 2023-09-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_rename_article_scope_article_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="articles.article",
            ),
        ),
    ]
