# Generated by Django 4.2.5 on 2023-09-29 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_alter_scope_article_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scope",
            old_name="article_id",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="scope",
            old_name="tag_id",
            new_name="tag",
        ),
    ]
