# Generated by Django 4.2.5 on 2023-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0012_alter_scope_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
