# Generated by Django 4.2.5 on 2023-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_rename_teacher_id_student_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ManyToManyField(related_name="teachers", to="school.teacher"),
        ),
    ]
