# Generated by Django 4.2.5 on 2023-09-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_rename_teacher_student_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="students", to="school.teacher"),
        ),
    ]
